version: '3.9'

services:

  # Keycloak - Identity and Access Management solution
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    ports:
      - "8001:8080"
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}

      KC_HOSTNAME_DEBUG: ${KC_HOSTNAME_DEBUG}

      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_PORT: 8001
      KC_HOSTNAME_STRICT: true
      KC_HOSTNAME_STRICT_HTTPS: true


      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - components_network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 60s
    depends_on:
      - keycloak_db
  keycloak_db:
    container_name: keycloak_db
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "54320:5432"
    networks:
      - components_network
    volumes:
      - /components_data/keycloak_postgres:/var/lib/postgresql/data
networks:
  components_network:
    external: true
