version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - components_network
networks:
  components_network:
    external: true
