version: '3.9'

services:
  otel-collector:
    container_name: otel_collector
    image: otel/opentelemetry-collector-contrib:0.90.0
    command: [ "--config=/etc/otel_collector/otel-collector-config.yaml" ]
    volumes:
      - /components/observability/otel_collector:/etc/otel_collector
    environment:
      - EXPORT_ENDPOINT=http://grafana_tempo:4317
      - LOKI_ENDPOINT=http://grafana_loki:3100
    networks:
      - components_network
    ports:
      - "4317:4317" # OTLP gRPC receiver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.20'
          memory: 250M
        reservations:
          cpus: '0.10'
          memory: 135M

  # Grafana dashboard
  grafana:
    container_name: grafana
    image: grafana/grafana:11.4.0
    user: root
    networks:
      - components_network
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    volumes:
      - /components/observability/grafana:/etc/grafana
      - /components_data/observability/grafana:/var/lib/grafana
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.40'
          memory: 500M
        reservations:
          cpus: '0.10'
          memory: 200M


  # Grafana Loki - log aggregation system
  # https://grafana.com/oss/loki/
  grafana-loki:
    container_name: grafana_loki
    image: grafana/loki:3.3.0
    user: root
    command: [
      "-print-config-stderr",
      "-config.file=/etc/loki/local-config.yaml"
    ]
    ports:
      - "3100:3100"
    networks:
      - components_network
    volumes:
      - /components/observability/grafana_loki:/etc/loki
      - /components_data/observability/grafana_loki:/loki
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.20'
          memory: 250M
        reservations:
          cpus: '0.10'
          memory: 135M

  # Grafana Tempo - tracing backend
  # https://grafana.com/oss/tempo/
  grafana-tempo:
    container_name: grafana_tempo
    image: grafana/tempo:2.2.4
    user: root
    command: [
      "-distributor.log-received-spans.enabled",
      "-distributor.log-received-spans.include-attributes",
      "-server.http-listen-port=3200",
      "-storage.trace.backend=local",
      "-storage.trace.local.path=/tmp/tempo/blocks",
      "-storage.trace.wal.path=/tmp/tempo/wal"
    ]
    volumes:
      - /components_data/observability/grafana_tempo:/tmp/tempo
    ports:
      - "3200:3200"  # tempo
      - "4320:4317"  # otlp grpc
    networks:
      - components_network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.20'
          memory: 250M
        reservations:
          cpus: '0.10'
          memory: 135M

networks:
  components_network:
    external: true
