receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: ${env:EXPORT_ENDPOINT}
    tls:
      insecure: true
  otlphttp:
    endpoint: ${env:LOKI_ENDPOINT}/otlp

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp, logging ]
    logs:
      receivers: [ otlp ]
      exporters: [ otlphttp, logging ]
  telemetry:
    logs:
      level: debug
