apiVersion: 1

datasources:

    - name: Tempo
      type: tempo
      access: proxy
      orgId: 1
      url: http://grafana_tempo:3200
      basicAuth: false
      isDefault: false
      version: 1
      editable: false
      apiVersion: 1
      uid: tempo
      jsonData:
          httpMethod: GET

    - name: Loki
      type: loki
      uid: loki
      access: proxy
      orgId: 1
      url: http://grafana_loki:3100
      basicAuth: false
      isDefault: true
      version: 1
      editable: false
      apiVersion: 1
      jsonData:
        derivedFields:
          -   datasourceUid: tempo
              matcherRegex: \[.+,(.+?),
              name: TraceID
              url: $${__value.raw}
