version: '3.9'

services:

  otel-collector:
    container_name: otel-collector
    image: "${CONTAINER_REGISTRY_URL}/otel-collector:1.0"
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - "4317:4317"
    environment:
      - EXPORT_ENDPOINT=${EXPORT_ENDPOINT}:4317
      - LOKI_ENDPOINT=${LOKI_HOST}/loki/api/v1/push
