version: '3.9'

services:

  otel-collector:
    container_name: otel_collector
    image: otel/opentelemetry-collector-contrib:0.90.1
    command: [ "--config=/etc/otel_collector/otel-collector-config.yaml" ]
    ports:
      - "4317:4317"
    environment:
      - EXPORT_ENDPOINT=${EXPORT_ENDPOINT}:4317
      - LOKI_ENDPOINT=${LOKI_HOST}
    networks:
      - components_network
    volumes:
      - /components/otel_collector:/etc/otel_collector
networks:
  components_network:
    external: true
