receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: container
      - action: insert
        key: loki.format
        value: raw

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: ${env:EXPORT_ENDPOINT}
    tls:
      insecure: true
  loki:
    endpoint: ${env:LOKI_ENDPOINT}

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp, logging ]
    logs:
      receivers: [ otlp ]
      processors: [ attributes ]
      exporters: [ loki, logging ]
  telemetry:
    logs:
      level: debug
