version: '3.9'

services:

  # Grafana Loki - log aggregation system
  # https://grafana.com/oss/loki/
  grafana-loki:
    container_name: grafana_loki
    image: grafana/loki:3.3.0
    command: [
      "-print-config-stderr",
      "-config.file=/etc/loki/local-config.yaml"
    ]
    ports:
      - "3100:3100"
    networks:
      - components_network
    volumes:
      - /tmp/observability/loki-data/:/loki
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.20'
          memory: 250M
        reservations:
          cpus: '0.10'
          memory: 135M

  # Grafana Tempo - tracing backend
  # https://grafana.com/oss/tempo/
  grafana-tempo:
    container_name: grafana_tempo
    image: grafana/tempo:2.2.4
    command: [
      "-distributor.log-received-spans.enabled",
      "-distributor.log-received-spans.include-attributes",
      "-server.http-listen-port=3200",
      "-storage.trace.backend=local",
      "-storage.trace.local.path=/tmp/tempo/blocks",
      "-storage.trace.wal.path=/tmp/tempo/wal"
    ]
    volumes:
      - /tmp/observability/tempo-data:/tmp/tempo
    ports:
      - "3200:3200"  # tempo
      - "4317:4317"  # otlp grpc
    networks:
      - components_network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.20'
          memory: 250M
        reservations:
          cpus: '0.10'
          memory: 135M

networks:
  components_network:
    external: true
