version: '3.9'

services:

  # Consul - service networking solution to automate network configurations,
  # discover services, and enable secure connectivity across any cloud or runtime
  consul:
    container_name: consul
    image: consul:1.15.4
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    # TODO Implement persistent storage for all configs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 35M
